# Analysis of experiment #1: DPCP heuristics

## Data

In [1]:
# Read csv

import pandas as pd

df = pd.read_csv("out/stats.csv")

# Some renames to improve readability
df["solver"] = df["solver"].str.replace("v2", "deg")
df["solver"] = df["solver"].str.replace("v3", "edg")

# For the unsolved instances,
# --> write NaN in ub
# --> write NaN in bestTime
# --> write NaN in bestIter
df.loc[df.state != "FEASIBLE", "ub"] = float("nan")
df.loc[df.state != "FEASIBLE", "bestTime"] = float("nan")
df.loc[df.state != "FEASIBLE", "bestIter"] = float("nan")

# Rename some columns
df = df.rename(columns={'ub': 'value', 'state': 'solved'})

# df = df[~df.solver.isin(["heur_semigreedy2s_deg_r1000","heur_semigreedy2s_edg_r1000"])]

df

,instance,solver,run,nvertices,nedges,nA,nB,nvars,ncons,solved,...,otherNodesNColsHeur,otherNodesNColsMwis1,otherNodesNColsMwis2,otherNodesNColsExact,otherNodesTime,otherNodesTimePool,otherNodesTimeHeur,otherNodesTimeMwis1,otherNodesTimeMwis2,otherNodesTimeExact
0,r_n100_p0.75_nA10_nB10_i0,heur_greedy2s_deg,0,100,3704,10,10,-1,-1,FEASIBLE,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,r_n150_p0.75_nA15_nB15_i0,heur_greedy2s_deg,0,150,8340,15,15,-1,-1,FEASIBLE,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,r_n150_p0.5_nA30_nB15_i0,heur_greedy2s_deg,0,150,5525,30,15,-1,-1,FEASIBLE,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,r_n100_p0.25_nA10_nB10_i1,heur_greedy2s_deg,0,100,1262,10,10,-1,-1,FEASIBLE,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
4,r_n100_p0.25_nA10_nB20_i1,heur_greedy2s_deg,0,100,1239,10,20,-1,-1,FEASIBLE,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
643,r_n100_p0.5_nA20_nB20_i0,heur_greedy1s,0,100,2500,20,20,-1,-1,FEASIBLE,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
644,r_n100_p0.75_nA10_nB10_i1,heur_greedy1s,0,100,3687,10,10,-1,-1,FEASIBLE,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
645,r_n100_p0.75_nA20_nB10_i2,heur_greedy1s,0,100,3720,20,10,-1,-1,INFEASIBLE,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
646,r_n100_p0.5_nA20_nB20_i1,heur_greedy1s,0,100,2554,20,20,-1,-1,FEASIBLE,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
647,r_n100_p0.5_nA10_nB20_i2,heur_greedy1s,0,100,2490,10,20,-1,-1,FEASIBLE,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

## Best

In [2]:
# Pivot dataframe
df2 = df.pivot(index="instance", columns="solver", values=["value","bestTime"])
df2

                                  value                                      \
solver                    heur_greedy1s heur_greedy2s_deg heur_greedy2s_edg
instance
r_n100_p0.25_nA10_nB10_i0           2.0               3.0               1.0
r_n100_p0.25_nA10_nB10_i1           2.0               2.0               2.0
r_n100_p0.25_nA10_nB10_i2           1.0               2.0               2.0
r_n100_p0.25_nA10_nB20_i0           2.0               2.0               2.0
r_n100_p0.25_nA10_nB20_i1           1.0               2.0               1.0
...                                 ...               ...               ...
r_n150_p0.75_nA30_nB15_i1           NaN               NaN               NaN
r_n150_p0.75_nA30_nB15_i2           NaN               NaN              13.0
r_n150_p0.75_nA30_nB30_i0           NaN              10.0              12.0
r_n150_p0.75_nA30_nB30_i1           NaN              11.0              12.0
r_n150_p0.75_nA30_nB30_i2           NaN              11.0              12.0

                                                     \
solver                    heur_semigreedy2s_deg_r10
instance
r_n100_p0.25_nA10_nB10_i0                       2.0
r_n100_p0.25_nA10_nB10_i1                       2.0
r_n100_p0.25_nA10_nB10_i2                       2.0
r_n100_p0.25_nA10_nB20_i0                       1.0
r_n100_p0.25_nA10_nB20_i1                       2.0
...                                             ...
r_n150_p0.75_nA30_nB15_i1                      14.0
r_n150_p0.75_nA30_nB15_i2                      10.0
r_n150_p0.75_nA30_nB30_i0                       9.0
r_n150_p0.75_nA30_nB30_i1                      10.0
r_n150_p0.75_nA30_nB30_i2                      10.0

                                                      \
solver                    heur_semigreedy2s_deg_r100
instance
r_n100_p0.25_nA10_nB10_i0                        2.0
r_n100_p0.25_nA10_nB10_i1                        2.0
r_n100_p0.25_nA10_nB10_i2                        2.0
r_n100_p0.25_nA10_nB20_i0                        1.0
r_n100_p0.25_nA10_nB20_i1                        2.0
...                                              ...
r_n150_p0.75_nA30_nB15_i1                       13.0
r_n150_p0.75_nA30_nB15_i2                       10.0
r_n150_p0.75_nA30_nB30_i0                        9.0
r_n150_p0.75_nA30_nB30_i1                       10.0
r_n150_p0.75_nA30_nB30_i2                        9.0

                                                       \
solver                    heur_semigreedy2s_deg_r1000
instance
r_n100_p0.25_nA10_nB10_i0                         1.0
r_n100_p0.25_nA10_nB10_i1                         2.0
r_n100_p0.25_nA10_nB10_i2                         2.0
r_n100_p0.25_nA10_nB20_i0                         1.0
r_n100_p0.25_nA10_nB20_i1                         2.0
...                                               ...
r_n150_p0.75_nA30_nB15_i1                        12.0
r_n150_p0.75_nA30_nB15_i2                        10.0
r_n150_p0.75_nA30_nB30_i0                         8.0
r_n150_p0.75_nA30_nB30_i1                         9.0
r_n150_p0.75_nA30_nB30_i2                         9.0

                                                     \
solver                    heur_semigreedy2s_edg_r10
instance
r_n100_p0.25_nA10_nB10_i0                       1.0
r_n100_p0.25_nA10_nB10_i1                       2.0
r_n100_p0.25_nA10_nB10_i2                       1.0
r_n100_p0.25_nA10_nB20_i0                       1.0
r_n100_p0.25_nA10_nB20_i1                       1.0
...                                             ...
r_n150_p0.75_nA30_nB15_i1                       NaN
r_n150_p0.75_nA30_nB15_i2                       NaN
r_n150_p0.75_nA30_nB30_i0                      11.0
r_n150_p0.75_nA30_nB30_i1                      10.0
r_n150_p0.75_nA30_nB30_i2                      10.0

                                                      \
solver                    heur_semigreedy2s_edg_r100
instance
r_n100_p0.25_nA10_nB10_i0                        1.0
r_n100_p0.25_nA10_nB10_i1                        1.0
r_n100_p0.25_nA10_nB10_i2                        1.0
r_n100_p0.25_nA10_nB20_i0                        1.0
r_n100_p0.25_nA10_nB20_i1                        1.0
...                                              ...
r_n150_p0.75_nA30_nB15_i1                       12.0
r_n150_p0.75_nA30_nB15_i2                       11.0
r_n150_p0.75_nA30_nB30_i0                       10.0
r_n150_p0.75_nA30_nB30_i1                       10.0
r_n150_p0.75_nA30_nB30_i2                       10.0

                                                           bestTime  \
solver                    heur_semigreedy2s_edg_r1000 heur_greedy1s
instance
r_n100_p0.25_nA10_nB10_i0                         1.0      0.000591
r_n100_p0.25_nA10_nB10_i1                         1.0      0.000621
r_n100_p0.25_nA10_nB10_i2                         1.0      0.000571
r_n100_p0.25_nA10_nB20_i0                         1.0      0.000705
r_n100_p0.25_nA10_nB20_i1                         1.0      0.000690
...                                               ...           ...
r_n150_p0.75_nA30_nB15_i1                        12.0           NaN
r_n150_p0.75_nA30_nB15_i2                        11.0           NaN
r_n150_p0.75_nA30_nB30_i0                         9.0           NaN
r_n150_p0.75_nA30_nB30_i1                         9.0           NaN
r_n150_p0.75_nA30_nB30_i2                         9.0           NaN

                                                               \
solver                    heur_greedy2s_deg heur_greedy2s_edg
instance
r_n100_p0.25_nA10_nB10_i0          0.000213          0.000135
r_n100_p0.25_nA10_nB10_i1          0.000243          0.000125
r_n100_p0.25_nA10_nB10_i2          0.000179          0.000117
r_n100_p0.25_nA10_nB20_i0          0.000202          0.000127
r_n100_p0.25_nA10_nB20_i1          0.000197          0.000124
...                                     ...               ...
r_n150_p0.75_nA30_nB15_i1               NaN               NaN
r_n150_p0.75_nA30_nB15_i2               NaN          0.001009
r_n150_p0.75_nA30_nB30_i0          0.001396          0.001406
r_n150_p0.75_nA30_nB30_i1          0.001544          0.001454
r_n150_p0.75_nA30_nB30_i2          0.001377          0.001416

                                                     \
solver                    heur_semigreedy2s_deg_r10
instance
r_n100_p0.25_nA10_nB10_i0                  0.000204
r_n100_p0.25_nA10_nB10_i1                  0.000160
r_n100_p0.25_nA10_nB10_i2                  0.000216
r_n100_p0.25_nA10_nB20_i0                  0.001342
r_n100_p0.25_nA10_nB20_i1                  0.000178
...                                             ...
r_n150_p0.75_nA30_nB15_i1                  0.004053
r_n150_p0.75_nA30_nB15_i2                  0.004350
r_n150_p0.75_nA30_nB30_i0                  0.001101
r_n150_p0.75_nA30_nB30_i1                  0.001151
r_n150_p0.75_nA30_nB30_i2                  0.002289

                                                      \
solver                    heur_semigreedy2s_deg_r100
instance
r_n100_p0.25_nA10_nB10_i0                   0.000200
r_n100_p0.25_nA10_nB10_i1                   0.000160
r_n100_p0.25_nA10_nB10_i2                   0.000158
r_n100_p0.25_nA10_nB20_i0                   0.001352
r_n100_p0.25_nA10_nB20_i1                   0.000177
...                                              ...
r_n150_p0.75_nA30_nB15_i1                   0.011126
r_n150_p0.75_nA30_nB15_i2                   0.004542
r_n150_p0.75_nA30_nB30_i0                   0.001160
r_n150_p0.75_nA30_nB30_i1                   0.001141
r_n150_p0.75_nA30_nB30_i2                   0.070605

                                                       \
solver                    heur_semigreedy2s_deg_r1000
instance
r_n100_p0.25_nA10_nB10_i0                    0.019096
r_n100_p0.25_nA10_nB10_i1                    0.000190
r_n100_p0.25_nA10_nB10_i2                    0.000160
r_n100_p0.25_nA10_nB20_i0                    0.001346
r_n100_p0.25_nA10_nB20_i1                    0.000179
...                                               ...
r_n150_p0.75_nA30_nB15_i1                    0.158905
r_n150_p0.75_nA30_nB15_i2                    0.004574
r_n150_p0.75_nA30_nB30_i0                    0.174865
r_n150_p0.75_nA30_nB30_i1                    0.150308
r_n150_p0.75_nA30_nB30_i2                    0.069594

                                                     \
solver                    heur_semigreedy2s_edg_r10
instance
r_n100_p0.25_nA10_nB10_i0                  0.000090
r_n100_p0.25_nA10_nB10_i1                  0.000090
r_n100_p0.25_nA10_nB10_i2                  0.000361
r_n100_p0.25_nA10_nB20_i0                  0.000171
r_n100_p0.25_nA10_nB20_i1                  0.000123
...                                             ...
r_n150_p0.75_nA30_nB15_i1                       NaN
r_n150_p0.75_nA30_nB15_i2                       NaN
r_n150_p0.75_nA30_nB30_i0                  0.001005
r_n150_p0.75_nA30_nB30_i1                  0.004350
r_n150_p0.75_nA30_nB30_i2                  0.000960

                                                      \
solver                    heur_semigreedy2s_edg_r100
instance
r_n100_p0.25_nA10_nB10_i0                   0.000090
r_n100_p0.25_nA10_nB10_i1                   0.000975
r_n100_p0.25_nA10_nB10_i2                   0.000409
r_n100_p0.25_nA10_nB20_i0                   0.000169
r_n100_p0.25_nA10_nB20_i1                   0.000095
...                                              ...
r_n150_p0.75_nA30_nB15_i1                   0.004582
r_n150_p0.75_nA30_nB15_i2                   0.008231
r_n150_p0.75_nA30_nB30_i0                   0.026243
r_n150_p0.75_nA30_nB30_i1                   0.004329
r_n150_p0.75_nA30_nB30_i2                   0.000951


solver                    heur_semigreedy2s_edg_r1000
instance
r_n100_p0.25_nA10_nB10_i0                    0.000125
r_n100_p0.25_nA10_nB10_i1                    0.000983
r_n100_p0.25_nA10_nB10_i2                    0.000370
r_n100_p0.25_nA10_nB20_i0                    0.000174
r_n100_p0.25_nA10_nB20_i1                    0.000095
...                                               ...
r_n150_p0.75_nA30_nB15_i1                    0.004899
r_n150_p0.75_nA30_nB15_i2                    0.008328
r_n150_p0.75_nA30_nB30_i0                    0.262897
r_n150_p0.75_nA30_nB30_i1                    0.388852
r_n150_p0.75_nA30_nB30_i2                    0.241895

[72 rows x 18 columns]

In [3]:
# Comparison function
def get_winner_heur(row):
    best_heur = None
    min_value = float("inf")
    min_time = float("inf")
    n_heurs = int(len(row)/2)
    for i in range(n_heurs):
        h = df2.columns[i][1] # get heuristic's name
        j = ("bestTime", h) # get column's name of the bestTime for h
        if (row.iloc[i] < min_value) or (row.iloc[i] == min_value and row[j] < min_time):
            best_heur = h
            min_value = row.iloc[i]
            min_time = row[j]
    return best_heur

In [4]:
df2["winner"] = df2.apply(get_winner_heur, axis=1)
df2

                                  value                                      \
solver                    heur_greedy1s heur_greedy2s_deg heur_greedy2s_edg
instance
r_n100_p0.25_nA10_nB10_i0           2.0               3.0               1.0
r_n100_p0.25_nA10_nB10_i1           2.0               2.0               2.0
r_n100_p0.25_nA10_nB10_i2           1.0               2.0               2.0
r_n100_p0.25_nA10_nB20_i0           2.0               2.0               2.0
r_n100_p0.25_nA10_nB20_i1           1.0               2.0               1.0
...                                 ...               ...               ...
r_n150_p0.75_nA30_nB15_i1           NaN               NaN               NaN
r_n150_p0.75_nA30_nB15_i2           NaN               NaN              13.0
r_n150_p0.75_nA30_nB30_i0           NaN              10.0              12.0
r_n150_p0.75_nA30_nB30_i1           NaN              11.0              12.0
r_n150_p0.75_nA30_nB30_i2           NaN              11.0              12.0

                                                     \
solver                    heur_semigreedy2s_deg_r10
instance
r_n100_p0.25_nA10_nB10_i0                       2.0
r_n100_p0.25_nA10_nB10_i1                       2.0
r_n100_p0.25_nA10_nB10_i2                       2.0
r_n100_p0.25_nA10_nB20_i0                       1.0
r_n100_p0.25_nA10_nB20_i1                       2.0
...                                             ...
r_n150_p0.75_nA30_nB15_i1                      14.0
r_n150_p0.75_nA30_nB15_i2                      10.0
r_n150_p0.75_nA30_nB30_i0                       9.0
r_n150_p0.75_nA30_nB30_i1                      10.0
r_n150_p0.75_nA30_nB30_i2                      10.0

                                                      \
solver                    heur_semigreedy2s_deg_r100
instance
r_n100_p0.25_nA10_nB10_i0                        2.0
r_n100_p0.25_nA10_nB10_i1                        2.0
r_n100_p0.25_nA10_nB10_i2                        2.0
r_n100_p0.25_nA10_nB20_i0                        1.0
r_n100_p0.25_nA10_nB20_i1                        2.0
...                                              ...
r_n150_p0.75_nA30_nB15_i1                       13.0
r_n150_p0.75_nA30_nB15_i2                       10.0
r_n150_p0.75_nA30_nB30_i0                        9.0
r_n150_p0.75_nA30_nB30_i1                       10.0
r_n150_p0.75_nA30_nB30_i2                        9.0

                                                       \
solver                    heur_semigreedy2s_deg_r1000
instance
r_n100_p0.25_nA10_nB10_i0                         1.0
r_n100_p0.25_nA10_nB10_i1                         2.0
r_n100_p0.25_nA10_nB10_i2                         2.0
r_n100_p0.25_nA10_nB20_i0                         1.0
r_n100_p0.25_nA10_nB20_i1                         2.0
...                                               ...
r_n150_p0.75_nA30_nB15_i1                        12.0
r_n150_p0.75_nA30_nB15_i2                        10.0
r_n150_p0.75_nA30_nB30_i0                         8.0
r_n150_p0.75_nA30_nB30_i1                         9.0
r_n150_p0.75_nA30_nB30_i2                         9.0

                                                     \
solver                    heur_semigreedy2s_edg_r10
instance
r_n100_p0.25_nA10_nB10_i0                       1.0
r_n100_p0.25_nA10_nB10_i1                       2.0
r_n100_p0.25_nA10_nB10_i2                       1.0
r_n100_p0.25_nA10_nB20_i0                       1.0
r_n100_p0.25_nA10_nB20_i1                       1.0
...                                             ...
r_n150_p0.75_nA30_nB15_i1                       NaN
r_n150_p0.75_nA30_nB15_i2                       NaN
r_n150_p0.75_nA30_nB30_i0                      11.0
r_n150_p0.75_nA30_nB30_i1                      10.0
r_n150_p0.75_nA30_nB30_i2                      10.0

                                                      \
solver                    heur_semigreedy2s_edg_r100
instance
r_n100_p0.25_nA10_nB10_i0                        1.0
r_n100_p0.25_nA10_nB10_i1                        1.0
r_n100_p0.25_nA10_nB10_i2                        1.0
r_n100_p0.25_nA10_nB20_i0                        1.0
r_n100_p0.25_nA10_nB20_i1                        1.0
...                                              ...
r_n150_p0.75_nA30_nB15_i1                       12.0
r_n150_p0.75_nA30_nB15_i2                       11.0
r_n150_p0.75_nA30_nB30_i0                       10.0
r_n150_p0.75_nA30_nB30_i1                       10.0
r_n150_p0.75_nA30_nB30_i2                       10.0

                                                           bestTime  \
solver                    heur_semigreedy2s_edg_r1000 heur_greedy1s
instance
r_n100_p0.25_nA10_nB10_i0                         1.0      0.000591
r_n100_p0.25_nA10_nB10_i1                         1.0      0.000621
r_n100_p0.25_nA10_nB10_i2                         1.0      0.000571
r_n100_p0.25_nA10_nB20_i0                         1.0      0.000705
r_n100_p0.25_nA10_nB20_i1                         1.0      0.000690
...                                               ...           ...
r_n150_p0.75_nA30_nB15_i1                        12.0           NaN
r_n150_p0.75_nA30_nB15_i2                        11.0           NaN
r_n150_p0.75_nA30_nB30_i0                         9.0           NaN
r_n150_p0.75_nA30_nB30_i1                         9.0           NaN
r_n150_p0.75_nA30_nB30_i2                         9.0           NaN

                                                               \
solver                    heur_greedy2s_deg heur_greedy2s_edg
instance
r_n100_p0.25_nA10_nB10_i0          0.000213          0.000135
r_n100_p0.25_nA10_nB10_i1          0.000243          0.000125
r_n100_p0.25_nA10_nB10_i2          0.000179          0.000117
r_n100_p0.25_nA10_nB20_i0          0.000202          0.000127
r_n100_p0.25_nA10_nB20_i1          0.000197          0.000124
...                                     ...               ...
r_n150_p0.75_nA30_nB15_i1               NaN               NaN
r_n150_p0.75_nA30_nB15_i2               NaN          0.001009
r_n150_p0.75_nA30_nB30_i0          0.001396          0.001406
r_n150_p0.75_nA30_nB30_i1          0.001544          0.001454
r_n150_p0.75_nA30_nB30_i2          0.001377          0.001416

                                                     \
solver                    heur_semigreedy2s_deg_r10
instance
r_n100_p0.25_nA10_nB10_i0                  0.000204
r_n100_p0.25_nA10_nB10_i1                  0.000160
r_n100_p0.25_nA10_nB10_i2                  0.000216
r_n100_p0.25_nA10_nB20_i0                  0.001342
r_n100_p0.25_nA10_nB20_i1                  0.000178
...                                             ...
r_n150_p0.75_nA30_nB15_i1                  0.004053
r_n150_p0.75_nA30_nB15_i2                  0.004350
r_n150_p0.75_nA30_nB30_i0                  0.001101
r_n150_p0.75_nA30_nB30_i1                  0.001151
r_n150_p0.75_nA30_nB30_i2                  0.002289

                                                      \
solver                    heur_semigreedy2s_deg_r100
instance
r_n100_p0.25_nA10_nB10_i0                   0.000200
r_n100_p0.25_nA10_nB10_i1                   0.000160
r_n100_p0.25_nA10_nB10_i2                   0.000158
r_n100_p0.25_nA10_nB20_i0                   0.001352
r_n100_p0.25_nA10_nB20_i1                   0.000177
...                                              ...
r_n150_p0.75_nA30_nB15_i1                   0.011126
r_n150_p0.75_nA30_nB15_i2                   0.004542
r_n150_p0.75_nA30_nB30_i0                   0.001160
r_n150_p0.75_nA30_nB30_i1                   0.001141
r_n150_p0.75_nA30_nB30_i2                   0.070605

                                                       \
solver                    heur_semigreedy2s_deg_r1000
instance
r_n100_p0.25_nA10_nB10_i0                    0.019096
r_n100_p0.25_nA10_nB10_i1                    0.000190
r_n100_p0.25_nA10_nB10_i2                    0.000160
r_n100_p0.25_nA10_nB20_i0                    0.001346
r_n100_p0.25_nA10_nB20_i1                    0.000179
...                                               ...
r_n150_p0.75_nA30_nB15_i1                    0.158905
r_n150_p0.75_nA30_nB15_i2                    0.004574
r_n150_p0.75_nA30_nB30_i0                    0.174865
r_n150_p0.75_nA30_nB30_i1                    0.150308
r_n150_p0.75_nA30_nB30_i2                    0.069594

                                                     \
solver                    heur_semigreedy2s_edg_r10
instance
r_n100_p0.25_nA10_nB10_i0                  0.000090
r_n100_p0.25_nA10_nB10_i1                  0.000090
r_n100_p0.25_nA10_nB10_i2                  0.000361
r_n100_p0.25_nA10_nB20_i0                  0.000171
r_n100_p0.25_nA10_nB20_i1                  0.000123
...                                             ...
r_n150_p0.75_nA30_nB15_i1                       NaN
r_n150_p0.75_nA30_nB15_i2                       NaN
r_n150_p0.75_nA30_nB30_i0                  0.001005
r_n150_p0.75_nA30_nB30_i1                  0.004350
r_n150_p0.75_nA30_nB30_i2                  0.000960

                                                      \
solver                    heur_semigreedy2s_edg_r100
instance
r_n100_p0.25_nA10_nB10_i0                   0.000090
r_n100_p0.25_nA10_nB10_i1                   0.000975
r_n100_p0.25_nA10_nB10_i2                   0.000409
r_n100_p0.25_nA10_nB20_i0                   0.000169
r_n100_p0.25_nA10_nB20_i1                   0.000095
...                                              ...
r_n150_p0.75_nA30_nB15_i1                   0.004582
r_n150_p0.75_nA30_nB15_i2                   0.008231
r_n150_p0.75_nA30_nB30_i0                   0.026243
r_n150_p0.75_nA30_nB30_i1                   0.004329
r_n150_p0.75_nA30_nB30_i2                   0.000951

                                                       \
solver                    heur_semigreedy2s_edg_r1000
instance
r_n100_p0.25_nA10_nB10_i0                    0.000125
r_n100_p0.25_nA10_nB10_i1                    0.000983
r_n100_p0.25_nA10_nB10_i2                    0.000370
r_n100_p0.25_nA10_nB20_i0                    0.000174
r_n100_p0.25_nA10_nB20_i1                    0.000095
...                                               ...
r_n150_p0.75_nA30_nB15_i1                    0.004899
r_n150_p0.75_nA30_nB15_i2                    0.008328
r_n150_p0.75_nA30_nB30_i0                    0.262897
r_n150_p0.75_nA30_nB30_i1                    0.388852
r_n150_p0.75_nA30_nB30_i2                    0.241895

                                                winner
solver
instance
r_n100_p0.25_nA10_nB10_i0   heur_semigreedy2s_edg_r100
r_n100_p0.25_nA10_nB10_i1   heur_semigreedy2s_edg_r100
r_n100_p0.25_nA10_nB10_i2    heur_semigreedy2s_edg_r10
r_n100_p0.25_nA10_nB20_i0   heur_semigreedy2s_edg_r100
r_n100_p0.25_nA10_nB20_i1   heur_semigreedy2s_edg_r100
...                                                ...
r_n150_p0.75_nA30_nB15_i1   heur_semigreedy2s_edg_r100
r_n150_p0.75_nA30_nB15_i2    heur_semigreedy2s_deg_r10
r_n150_p0.75_nA30_nB30_i0  heur_semigreedy2s_deg_r1000
r_n150_p0.75_nA30_nB30_i1  heur_semigreedy2s_deg_r1000
r_n150_p0.75_nA30_nB30_i2  heur_semigreedy2s_deg_r1000

[72 rows x 19 columns]

In [5]:
df["winner"] = df.apply(lambda row: row.solver == df2.loc[row.instance].winner, axis=1)
df

,instance,solver,run,nvertices,nedges,nA,nB,nvars,ncons,solved,...,otherNodesNColsMwis1,otherNodesNColsMwis2,otherNodesNColsExact,otherNodesTime,otherNodesTimePool,otherNodesTimeHeur,otherNodesTimeMwis1,otherNodesTimeMwis2,otherNodesTimeExact,winner
0,r_n100_p0.75_nA10_nB10_i0,heur_greedy2s_deg,0,100,3704,10,10,-1,-1,FEASIBLE,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,False
1,r_n150_p0.75_nA15_nB15_i0,heur_greedy2s_deg,0,150,8340,15,15,-1,-1,FEASIBLE,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,False
2,r_n150_p0.5_nA30_nB15_i0,heur_greedy2s_deg,0,150,5525,30,15,-1,-1,FEASIBLE,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,False
3,r_n100_p0.25_nA10_nB10_i1,heur_greedy2s_deg,0,100,1262,10,10,-1,-1,FEASIBLE,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,False
4,r_n100_p0.25_nA10_nB20_i1,heur_greedy2s_deg,0,100,1239,10,20,-1,-1,FEASIBLE,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
643,r_n100_p0.5_nA20_nB20_i0,heur_greedy1s,0,100,2500,20,20,-1,-1,FEASIBLE,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,False
644,r_n100_p0.75_nA10_nB10_i1,heur_greedy1s,0,100,3687,10,10,-1,-1,FEASIBLE,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,False
645,r_n100_p0.75_nA20_nB10_i2,heur_greedy1s,0,100,3720,20,10,-1,-1,INFEASIBLE,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,False
646,r_n100_p0.5_nA20_nB20_i1,heur_greedy1s,0,100,2554,20,20,-1,-1,FEASIBLE,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,False
647,r_n100_p0.5_nA10_nB20_i2,heur_greedy1s,0,100,2490,10,20,-1,-1,FEASIBLE,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,False

## Summary

In [6]:
df3 = df.groupby(["nvertices","solver"]).agg(
    {
        "solved": [("count", lambda x: (x == "FEASIBLE").sum())],
        "winner": [("%", lambda x: (x == True).sum() / len(x) * 100)],
        "value": [("avg", "mean")],
        "time": [("avg", "mean")],
        "bestIter": [("avg", "mean")]
    }
).reset_index()
df3

,nvertices,solver,solved,winner,value,time,bestIter
,,,count,%,avg,avg,avg
0,100,heur_greedy1s,27,5.555556,3.555556,0.001137,0.000000
1,100,heur_greedy2s_deg,35,2.777778,4.400000,0.000346,0.000000
2,100,heur_greedy2s_edg,35,16.666667,4.228571,0.000251,0.000000
3,100,heur_semigreedy2s_deg_r10,35,0.000000,3.857143,0.002431,2.057143
4,100,heur_semigreedy2s_deg_r100,36,0.000000,3.638889,0.023592,13.166667
5,100,heur_semigreedy2s_deg_r1000,36,13.888889,3.388889,0.228117,88.777778
6,100,heur_semigreedy2s_edg_r10,36,11.111111,3.777778,0.001590,1.861111
7,100,heur_semigreedy2s_edg_r100,36,22.222222,3.444444,0.015341,10.527778
8,100,heur_semigreedy2s_edg_r1000,36,27.777778,3.333333,0.149338,60.777778
9,150,heur_greedy1s,27,5.555556,4.074074,0.002791,0.000000
10,150,heur_greedy2s_deg,33,0.000000,5.757576,0.000841,0.000000
11,150,heur_greedy2s_edg,35,2.777778,6.114286,0.000706,0.000000
12,150,heur_semigreedy2s_deg_r10,36,2.777778,5.611111,0.006421,2.555556
13,150,heur_semigreedy2s_deg_r100,36,2.777778,5.194444,0.060910,15.333333
14,150,heur_semigreedy2s_deg_r1000,36,22.222222,4.888889,0.600494,100.555556
15,150,heur_semigreedy2s_edg_r10,34,13.888889,5.147059,0.004774,1.882353
16,150,heur_semigreedy2s_edg_r100,36,13.888889,5.166667,0.046601,11.611111
17,150,heur_semigreedy2s_edg_r1000,36,36.111111,4.777778,0.457761,176.583333